name: lgbm_py39_improve
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - _libgcc_mutex
  - _openmp_mutex
  - arrow-cpp
  - aws-c-cal
  - aws-c-common
  - aws-c-event-stream
  - aws-c-io
  - aws-checksums
  - aws-sdk-cpp
  - blas
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - fftw
  - gflags
  - glog
  - grpc-cpp
  - joblib
  - krb5
  - ld_impl_linux-64
  - libabseil
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libgoogle-cloud
  - libnghttp2
  - libnsl
  - libopenblas
  - libprotobuf
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-ng
  - libthrift
  - libutf8proc
  - libzlib
  - lightgbm
  - lz4-c
  - ncurses
  - numpy
  - numpy-base
  - openssl
  - orc
  - pandas
  - parquet-cpp
  - pip
  - pyarrow
  - python_abi
  - python-dateutil
  - pytz
  - pyyaml
  - re2
  - readline
  - s2n
  - scikit-learn
  - scipy
  - setuptools
  - six
  - snappy
  - sqlite
  - threadpoolctl
  - tk
  - wheel
  - xz
  - yaml
  - zlib
  - zstd